name: Build & Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v3

    - name: "Install dependencies"
      uses: php-actions/composer@v6

    - name: "Run PHP Unit tests"
      uses: php-actions/phpunit@v8
      with:
        php_extensions: xdebug
        bootstrap: vendor/autoload.php
        configuration: test/phpunit.xml
        args: --coverage-text
      env:
        XDEBUG_MODE: coverage