name: Build & Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v3

    - name: "Install dependencies and run phpunit"
      run: |
        php composer.phar --no-plugins --no-scripts install
        ./vendor/bin/phpunit --configuration phpunit.xml --coverage-text
      env:
        XDEBUG_MODE: coverage